### ISSUE TITLE
modimporter priority broken?

### ISSUE THREAD

**Issue by micriley** [MagicGonads/sgg-mod-format#2]
I have a modutil.lua file with this header.
```-- IMPORT @ DEFAULT
-- PRIORITY 0

--[[
Mod: Mod Utility
Author: MagicGonads  etce etce etc
```

and my own script as:
```-- IMPORT @ DEFAULT
-- PRIORITY 150

Mod: BonusDarknessLevels
Author: Mike Riley(Turbo Cop) etce etce```

With matching modfiles.txt as such:
```To "Scripts/RoomManager.lua"
  Import "BonusDarknessLevels.lua"
```

But when imported I find this at the bottom of RoomManager.lua:
```
Import "../Mods/BonusDarknessLevels/BonusDarknessLevels.lua"
Import "../Mods/ModUtil/ModUtil.lua"
-- MODIFIED by Mod Importer @ 2020-05-07 21:02:45.223783
```

Priority Order has been ignored.  Instead alphabetical directory order (default python file tree search pattern) has been in place instead.

**Comment by AndreLouisIssa** [comment]
modimporter doesn't read the lua files
so "-- PRIORITY" doesn't mean anything anymore
add

`Load Priority 0`
some point before you import ModUtil
or
`Load Priority 150`
to some point in your modfile before you import your mod but after you import ModUtil

Or just manually load the sub-module after your main module by having its import statement below it in the modfile
