### ISSUE TITLE
Fails to detect game on MacOS

### ISSUE THREAD

**Issue by durandal42** [MagicGonads/sgg-mod-format#6]
The following line, which determines which game is being modded, doesn't work on MacOS:
`game = strup(gamedir.split("/")[-1])`

On MacOS, the path to my Hades Content folder looks like this: `SteamApps/common/Hades/Game.macOS.app/Contents/Resources/Content`
... so the script believes it's operating on a game called "Content", and doesn't know what to do with that.

I have replaced the above line with the following, and this has worked for me:
`game = strup(gamedir.replace("/Game.macOS.app/Contents/Resources", "").split("/")[-1])`

I have no idea if this generalizes back to Windows, or games other than Hades.

**Comment by AndreLouisIssa** [comment]
Future importer will use user setup to determine the game folder to avoid this kind of thing

**Comment by AndreLouisIssa** [comment]
Modimporter has an alias that includes Resources you can change to map to any game name you want, by default maps to Hades.
